"""Add columns

Revision ID: 1dd23d6da344
Revises: 8394955dd01a
Create Date: 2019-02-19 11:58:20.283928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd23d6da344'
down_revision = '8394955dd01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'role_id')
    # ### end Alembic commands ###
