"""Added login authentication

Revision ID:572065616626
Revises: c41f8d158c21
Create Date: 2019-02-17 23:52:51.437804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers,used by Alembic.
revision ='572065616626'
down_revision = 'c41f8d158c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',sa.Column('email',sa.String(length=255),nullable=True))
    op.add_column('users',sa.Column('pass_secure',sa.String(length=255),nullable=True))
    op.create_index(op.f('ix_users_email'),'users',['email'],unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'),table_name='users')
    op.drop_column('users','pass_secure')
    op.drop_column('users','email')
    # ### end Alembic commands ###
